### ISSUE TITLE
makesurface backlog

### ISSUE THREAD

**Issue by dnomadb** [mapbox/make-surface#24]
Packaged cleanly, `makesurface` would be a suite of tools for `raster --> vector`, optimized for use in Mapbox Vector Tiles and formatted as a CLI:

`makesurface <surface function> <arguments> --<options>`
### installable package
- [x] `pip install makesurface` https://github.com/mapbox/make-surface/issues/14
### Housekeeping
- [x] Remove ipython sketches (or preserve in a branch)
- [x] Modularize scripting functionality (move specific function to `/scripts')
- [x] Use `pyskel` as a framework for organizing code
### Integrating Functionality
- [x] Smooth stacked polygons (improvement on original functionality) https://github.com/mapbox/make-surface/issues/18
- [ ] Joy Divisioning https://github.com/mapbox/make-surface/issues/17
- [x] Triangular Latticing https://github.com/mapbox/make-surface/issues/20
- [ ] Modularization of classification https://github.com/mapbox/make-surface/issues/22
- [ ] Add natural break classification https://github.com/mapbox/make-surface/issues/19
- [x] Better handling of projections https://github.com/mapbox/make-surface/issues/23
- [x] Clean up printing of `CartoCSS` to stdout https://github.com/mapbox/make-surface/issues/25

cc: @ian29 @heyitsgarrett @andreasviglakis
